version: "3.9"
services:
  dev-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    networks:
      - dev-net
networks:
  dev-net: